# Simple Infura Configuration
# Just put your Infura API key here - that's all you need!

use_infura: true
infura_api_key: "YOUR_INFURA_API_KEY_HERE"  # Replace with your API key from infura.io
infura_network: "mainnet"

# Network ID will be set automatically based on network name
network_id: 1

# Infura-optimized settings
workers: 2          # Keep low for rate limiting
batch_size: 5       # Small batches work better with Infura
request_timeout: "30s"

# Parsing options
start_block: 18000000
end_block: 18000010
include_logs: true
include_traces: false

# Output
output_format: "json"
output_path: "./infura_output"

# Example for different networks:
---
# Sepolia testnet
use_infura: true
infura_api_key: "YOUR_API_KEY"
infura_network: "sepolia"
network_id: 11155111

---
# Polygon mainnet  
use_infura: true
infura_api_key: "YOUR_API_KEY"
infura_network: "polygon-mainnet"
network_id: 137
